### PR TITLE
Fix For Discord New No Discriminator

### PR DESCRIPTION
**Pull request by TheVisual**
- Fixes The Discriminator Issue if the user has updated there account.

### CODE REVIEW

**Comment by purpl3r0se** [comment]
This is still gonna detect them as a webhook isn't it? Because a webhook still has the username field.

**Comment by TheVisual** [comment]
@purpl3r0se I tested and it works feel free to test

**Comment by purpl3r0se** [comment]
> @purpl3r0se I tested and it works feel free to test

I would but I don't have .NET installed on VS since I recently reinstalled.

**Comment by purpl3r0se** [comment]
@TheVisual told you
image

**Comment by TheVisual** [comment]
@purpl3r0se 

image

You're wrong.

**Comment by purpl3r0se** [comment]
> @purpl3r0se
> 
> image
> 
> You're wrong.

Well do they have the new username feature?

**Comment by TheVisual** [comment]
run  this code @purpl3r0se 

DiscordClient client = new DiscordClient("Token Here");

Console.WriteLine(client.User.Type);

**Comment by purpl3r0se** [comment]
image

**Comment by TheVisual** [comment]
Did you build from my source?

**Comment by purpl3r0se** [comment]
> Did you build from my source?

Yeah

**Comment by TheVisual** [comment]
@purpl3r0se try now 👍  with new build

**Comment by purpl3r0se** [comment]
Id won't be 0, webhooks have an ID

**Comment by TheVisual** [comment]
@purpl3r0se 
image

**Comment by purpl3r0se** [comment]
image

**Comment by TheVisual** [comment]
did you even try my build

**Comment by purpl3r0se** [comment]
> did you even try my build

What's the point if ID will never be 0

**Comment by TheVisual** [comment]
@purpl3r0se try it before you comment thanks 👍

**Comment by purpl3r0se** [comment]
> @purpl3r0se try it before you comment thanks 👍

As I said you just break functionality of it, now webhooks are detected as bots
image

**Comment by TheVisual** [comment]
@purpl3r0se try this also don't be rude i'm trying to help.

**Comment by purpl3r0se** [comment]
Now that change is just plain stupid, that's checking your LOCAL CLIENT's email & you wouldn't even be able to access someone else's email?

**Comment by TheVisual** [comment]
@purpl3r0se if you can do better do it urself bud.

**Comment by purpl3r0se** [comment]
will do later

**Comment by TheVisual** [comment]
@purpl3r0se yea sure. LOL stop being cocky and get off my pull request.

**Comment by purpl3r0se** [comment]
> @purpl3r0se yea sure. LOL stop being cocky and get off my pull request.

I mean it seems like all you've done so far is make a useless pull request that breaks other functionality.

**Comment by TheVisual** [comment]
@purpl3r0se and it seems your talking alot of shit for someone who can't do shit. I'm trying to help stop acting like a fucking child bro.

**Comment by purpl3r0se** [comment]
> @purpl3r0se and it seems your talking alot of shit for someone who can't do shit. I'm trying to help stop acting like a fucking child bro.

> who can't do shit
ok ill make a pull request in a bit, just gotta figure out how to migrate some stuff to new funcs

**Comment by TheVisual** [comment]
@purpl3r0se should be solved 👍 i generated like 50 + webhooks and they don't contain . or _ or -

**Comment by purpl3r0se** [comment]
> @purpl3r0se should be solved 👍 i generated like 50 + webhooks and they don't contain . only _ or -

I don't think you understand the code you're writing, the code you wrote is checking for your client's token (the one you logon with), and again you cannot access the webhook's token in any case without having it or having permissions in that server.

**Comment by purpl3r0se** [comment]
See #3366

**Comment by TheVisual** [comment]
@purpl3r0se well if you fixed it thats great i don't use webhooks 👍 i do know C# but not enough about webhooks i was trying to help.

**Comment by purpl3r0se** [comment]
> @purpl3r0se well if you fixed it thats great i don't use webhooks 👍 i do know C# but not enough about webhooks i was trying to help.

I don't know alot of C# but I know enough about the Discord API and I know other programming languages.

**Pull request closed without merging**
