### PR TITLE
Update ConnectedAccountType.cs to add more connection types.

### PR DESCRIPTION
**Pull request by cvyl**
New connections have been added, including a hidden PlayStation-Stg

### CODE REVIEW

**Comment by purpl3r0se** [comment]
@not-ilinked you should merge.

**Comment by purpl3r0se** [comment]
> New connections have been added, including a hidden PlayStation-Stg

PlayStation-Stg will cause an error because that's not the correct C# syntax, doesn't even seem like you checked if it works.

**Comment by purpl3r0se** [comment]
Fixed in #3366

**Comment by ptraced** [comment]
@not-ilinked should probably close this it's completed. 💪

**Pull request closed without merging**
