### PR TITLE
[WIP] Port To .Net 5

### PR DESCRIPTION
**Pull request by JReverse**
- Mostly working for Linux  / Windows (Untested on MAC)
- ~~The Package being used isn't fully supported for .Net 5 / .Net Core so ill be moving eventually~~ Use this... (https://workupload.com/file/khwah2sBsRL)
- Sockets are working not fully tested but works for most part

# NOTES
- FFMPEG / OPUS PROBABLY NOT WORKING (TODO)

### CODE REVIEW

**Comment by faith** [comment]
You can use GitHub actions for testing. It allows you to test from MacBook os too.

**Comment by baseds** [comment]
remove ur .vs folder bro

**Review by faith — CHANGES_REQUESTED** [review]
Seems like there is many useless files included in the .gitignore files.

**Comment by baseds** [comment]
It is auto generated, it just includes anything and everything that could be useless. Doesn't pose any threat being there.

**Comment by JReverse** [comment]
> Seems like there is many useless files included in the .gitignore file.

.gitignore is made by github...

**Comment by faith** [comment]
> > Seems like there is many useless files included in the .gitignore file.
> 
> .gitignore is made by github...

Its not made by github, any git repository can have one, its made to exclude files. However there is templates made by GitHub, if its a template its ok tho it seems to have some java related and more stuff thats why i said that it doesnt look like it would need all of these files excluded by .gitignore

**Comment by chefkochh** [comment]
I got my code to compile correctly but when i tried that on a rasperrypi or a linux machine it yelled at me with " websocket-sharp-with-proxy-support" not being compatible with net5.0 :thonk:

**Comment by chefkochh** [comment]
It dosent compile for me in linux: Its saying that Package websocket-sharp-with-proxy-support "is not compatible with net5.0 " lol

**Comment by JReverse** [comment]
> It dosent compile for me in linux: Its saying that Package websocket-sharp-with-proxy-support "is not compatible with net5.0 " lol

i only built on windows via visualstudio and outputted for linux and it worked idk about other stuff ass i said WIP

**Comment by chefkoch1337** [comment]
> 
> 
> > It dosent compile for me in linux: Its saying that Package websocket-sharp-with-proxy-support "is not compatible with net5.0 " lol
> 
> i only built on windows via visualstudio and outputted for linux and it worked idk about other stuff ass i said WIP

I dont want to be annoying or force you but if you could find any dotnet core version for websocketsharp and implement it, that would be great, no pressure or anything tho.

**Comment by JReverse** [comment]
@Femboyy https://workupload.com/file/khwah2sBsRL remove the old websharp nuget the betterwebsock one and replace with this

**Comment by not-ilinked** [comment]
is this port ready? i would love to have .net core support, but it has to be a complete port.

**Comment by JReverse** [comment]
@not-ilinked Almost i'll have to finish FFMPEG / OPEG support soon.

**Comment by sorashi** [comment]
@JReverse how is the work going? Is there any way I can help?

**Comment by JReverse** [comment]
@sorashi ffmpeg / opeg stuff for sounds is about the last thing.

**Comment by sorashi** [comment]
> 
> 
> Femboyy https://workupload.com/file/khwah2sBsRL remove the old websharp nuget the betterwebsock one and replace with this

@JReverse There are third-party netstandard nuget packages for websocketsharp: [WebSocketSharp-netstandard](https://www.nuget.org/packages/WebSocketSharp-netstandard/), [websocketsharp.core](https://www.nuget.org/packages/websocketsharp.core/), have you tried those?

**Comment by sorashi** [comment]
Furthermore, your current port drops support for .NET 4.7. Is that intentional? To broaden support, we could target [netstandard2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support).

In case we want to drop 4.7, all of the Example Projects should be upgraded to net5.

**Comment by JReverse** [comment]
@sorashi its the official ported to .net 5 also you should drop .net 4.7 .net core is the new age stuff

**Comment by sorashi** [comment]
> @sorashi its the official ported to .net 5 also you should drop .net 4.7 .net core is the new age stuff

That is opinionated. What about all the 4.7 projects relying on this library? @not-ilinked what is your stand?

**Comment by JReverse** [comment]
@sorashi you sound dumb no offense .net dosent support Linux or Mac .net core does

**Comment by sorashi** [comment]
> @sorashi you sound dumb no offense .net dosent support Linux or Mac .net core does

Ok, you don't understand, let's put it in simple terms:
netstandard2.0 is a standrad for libraries. It does not depend on 4.7 nor .net core. It's a STANDARD and a lot of frameworks can TARGET it including .net5 (multi-platform) AND .net framework.

**Comment by JReverse** [comment]
@sorashi you have 0 clue what you're talking about your spitting your shit preference on my pull request get off bro standard is mainly used for nuget shit he already said he would love .net support scroll up

**Comment by JReverse** [comment]
Also not to mention .net 4.8 is missing key feat foreach await and so on

**Comment by sorashi** [comment]
That's not preferences, it's broader support for libraries 🤦‍♂️ see the link I posted above. It's support for both net5 and net4.* AT THE SAME TIME. But I won't create any more "arguments", sorry for offering help, I'm out.

**Comment by JReverse** [comment]
@sorashi just stop meet 4.8 lacks tons of essential features

**Comment by sorashi** [comment]
Yeah sorry bye

**Comment by heapwalk** [comment]
Yea if you keep working on this pr you're basically just marinating in garbage, change it to .net standard please to avoid further issues when it comes to compatibility

**Comment by JReverse** [comment]
@heapwalk you sound dumb .net core is not garbage .net framework will not be updated to new version example .49 etc will not exist

Not to mention core has linux and also newer C# version

**Comment by heapwalk** [comment]
> @heapwalk you sound dumb .net core is not garbage .net framework will not be updated to new version example .49 etc will not exist
> 
> Not to mention core has linux and also newer C# version
> 
> Furthermore if you don't like what i do PORT it yourself kid.

Someone is mad, It's ok dude, brighter men than you have failed as well, It's just important that you learn from your mistakes

**Comment by JReverse** [comment]
@heapwalk Mad? 😂 nah, Not to mention you sound stupid. And what did I manage to "Fail at" Everything works on this except stuff regarding ffmpeg / opus as I use it myself on linux.

**Comment by JReverse** [comment]
I will continue when .net 6 comes out most likely

**Comment by JReverse** [comment]
Closing to work .net 6

**Pull request closed without merging**
