### PR TITLE
Changed to .net 5.0

### PR DESCRIPTION
**Pull request by aijkl**
Bots are often activated at all times
NET Framework can only be used on Windows, but .NET Core can be run on Linux.
I want to run Discord Bot on Linux.

### CODE REVIEW

**Comment by andreas-henning** [comment]
Thank you! I would love to see this accepted ASAP.

**Comment by aijkl** [comment]
I don't know if it will be accepted because it contains destructive changes

**Comment by Cthulhu-Admin** [comment]
> I don't know if it will be accepted because it contains destructive changes

Destructive in what sense?

Breaks existing projects and requires code changes?
Or breaks/removes features that currently work?

**Comment by Cthulhu-Admin** [comment]
@not-ilinked 
Any word on what the plan is with this? For me this would be a game changer. Zero interest in a Windows-Zero library. Huge interest if this is compatible with .NET 5 or 6.

**Comment by aijkl** [comment]
The disruptive change here is the disappearance of the Image class that existed in the .
https://github.com/not-ilinked/Anarchy/pull/3302/commits/d06967d6187870f3a599334cb54199f3949e09cb#diff-e95c280580aa062a220e365de761f449e27967b1a6720c3b822c95d3f4801547

**Comment by JReverse** [comment]
move to .net 6 has LTS

**Comment by Cthulhu-Admin** [comment]
> move to .net 6 has LTS

I so want this. Wish @not-ilinked could at least tell us where this is headed.

**Comment by JReverse** [comment]
Close this @aijkl already ported to .Net 6

**Comment by aijkl** [comment]
@andreas-henning @JReverse 
thank you for your work

**Pull request closed without merging**
