### PR TITLE
Adds a nitro sniper to examples

### PR DESCRIPTION
**Pull request by PBTada**
Includes a requested nitro sniper to the examples

### CODE REVIEW

**Comment by ytmcgamer** [comment]
ye

**Comment by ytmcgamer** [comment]
@not-ilinked

**Comment by not-ilinked** [comment]
u didnt need to do the HTTP req urself at the redeem part lol

anarchy has a RedeemGift method

**Comment by faith** [comment]
What else do u want in the examples? Ah yes a bot with 200 commands too. Make it urself hes not a slave

**Pull request closed without merging**
