### PR TITLE
Alot of additions/fixes/changes

### PR DESCRIPTION
**Pull request by verticalsync**
There's still a lot of stuff missing but hey at least it's more than what we had before, right?

- Added `Metadata` (`ConnectedAccountMetadata`) to `Connected Account` ([#d38781c](https://github.com/not-ilinked/Anarchy/pull/3366/commits/d38781cd60494b7da9d232952fd11106bf51efa9))
- Added new Connection Types ([#d38781c](https://github.com/not-ilinked/Anarchy/pull/3366/commits/d38781cd60494b7da9d232952fd11106bf51efa9))
- Added a new function called `ChangeAccountSettings` & `ChangeAccountSettingsAsync` ([#4950476](https://github.com/not-ilinked/Anarchy/pull/3366/commits/495047667f41d870941f8eae7f864bf69403a312))
- Moved most of the stuff from `ChangeProfileSettings` to `ChangeAccountSettings` because of an endpoint change for some of them. ([#4950476](https://github.com/not-ilinked/Anarchy/pull/3366/commits/495047667f41d870941f8eae7f864bf69403a312))
- Added `Basic` nitro type. ([#4950476](https://github.com/not-ilinked/Anarchy/pull/3366/commits/495047667f41d870941f8eae7f864bf69403a312))
- Added `LegacyUsername` to `DiscordUser` class ([#4950476](https://github.com/not-ilinked/Anarchy/pull/3366/commits/495047667f41d870941f8eae7f864bf69403a312))
- Fixed code where it detects users with the removal of discriminator as webhooks ([#4950476](https://github.com/not-ilinked/Anarchy/pull/3366/commits/495047667f41d870941f8eae7f864bf69403a312))
- Added code to throw an error on `GetProfile` if attempting to run it on a webhook user type ([#4950476](https://github.com/not-ilinked/Anarchy/pull/3366/commits/495047667f41d870941f8eae7f864bf69403a312))
- Added code to not display discriminator if there is none whenever using `ToString()` on the `DiscordUser` class ([#4950476](https://github.com/not-ilinked/Anarchy/pull/3366/commits/495047667f41d870941f8eae7f864bf69403a312))
- Added `DiscordUserProfileUser` class (weird name because it's hard to fit in with everything else) ([#475b936](https://github.com/not-ilinked/Anarchy/pull/3366/commits/475b9364eb059b77a2e62fd51a9e426e7aa8caac))
- Added `UserProfile`, `Nitro` and `BoostingSince` to `DiscordProfile` ([#475b936](https://github.com/not-ilinked/Anarchy/pull/3366/commits/475b9364eb059b77a2e62fd51a9e426e7aa8caac))
- Added `CertifiedModerator`, `Spammer` (not a badge see comment in code), `ActiveDeveloper` badge to `DiscordBadge` enum ([#475b936](https://github.com/not-ilinked/Anarchy/pull/3366/commits/475b9364eb059b77a2e62fd51a9e426e7aa8caac))
- Added `GlobalName`, `BannerColor`, `AccentColor`, `AvatarDecoration` to `DiscordProfileUser` ([#475b936](https://github.com/not-ilinked/Anarchy/pull/3366/commits/475b9364eb059b77a2e62fd51a9e426e7aa8caac))
- Added `Pronouns`, `Themecolors`, `PopoutAnimationParticleType`, `Emoji` to `DiscordUserProfileUser` class ([#475b936](https://github.com/not-ilinked/Anarchy/pull/3366/commits/475b9364eb059b77a2e62fd51a9e426e7aa8caac))
- Added `AccountSettingsUpdate` with a lot of stuff moved from `UserProfileUpdate` ([#475b936](https://github.com/not-ilinked/Anarchy/pull/3366/commits/475b9364eb059b77a2e62fd51a9e426e7aa8caac))
- Added `Forum` as a `ChannelType` ([#8809d3b](https://github.com/not-ilinked/Anarchy/pull/3366/commits/8809d3b29579b4f07a873b6fcef2be166ccf81ca))
- Added a bunch more Guild Permissions ([#8809d3b](https://github.com/not-ilinked/Anarchy/pull/3366/commits/8809d3b29579b4f07a873b6fcef2be166ccf81ca))
- Added a bunch more Discord Errors ([#8809d3b](https://github.com/not-ilinked/Anarchy/pull/3366/commits/8809d3b29579b4f07a873b6fcef2be166ccf81ca))
- Added `PaySafeCard` enum to `PaymentMethodType` enum (probably unusable, unsure.) ([#890b4da](https://github.com/not-ilinked/Anarchy/pull/3366/commits/890b4dad571f2b9ef6e95e2f1a919cb06847b4fc))
- Added `Nothing` enum to `GuildDefaultNotifications` enum ([#890b4da](https://github.com/not-ilinked/Anarchy/pull/3366/commits/890b4dad571f2b9ef6e95e2f1a919cb06847b4fc))
- Added function overload for `SendFriendRequest` so you can send a friend request without specifying a discriminator. ([#890b4da](https://github.com/not-ilinked/Anarchy/pull/3366/commits/890b4dad571f2b9ef6e95e2f1a919cb06847b4fc))
- Added `BasicMonthly` and `BasicYearly` to `DiscordNitroSubTypes` class ([#890b4da](https://github.com/not-ilinked/Anarchy/pull/3366/commits/890b4dad571f2b9ef6e95e2f1a919cb06847b4fc))
- Added a check for discriminator in `SendFriendRequestAsync` function inside of `DiscordUser` class ([#890b4da](https://github.com/not-ilinked/Anarchy/pull/3366/commits/890b4dad571f2b9ef6e95e2f1a919cb06847b4fc))
- Added `FailedToDecodePayload` enum to `DiscordMediaCloseCode` enum ([#3a44763](https://github.com/not-ilinked/Anarchy/pull/3366/commits/3a447630aa933d4a1ade570794f920424082180f))
- Added `Refunded` enum to `DiscordPaymentStatus` enum ([#0fc57cc](https://github.com/not-ilinked/Anarchy/pull/3366/commits/0fc57cc8a145f7cfd5c1a83e96ea2673dadb1aa6))

### CODE REVIEW

**Comment by TheVisual** [comment]
👍 We should Start porting to System.Text.Json soon its much faster and more efficient. I got halfway there but it's time consuming so I closed it for now.

**Comment by verticalsync** [comment]
> 👍 We should Start porting to System.Text.Json soon its much faster and more efficient. I got halfway there but it's time consuming so I closed it for now.

Honestly the entire library should probably undergo a rewrite because of changes and some names not really fitting so changing them would also cause a lot of breaking changes, but I doubt anyone's gonna bother doing that.

**Comment by TheVisual** [comment]
@verticalsync Are you able to implement the report abuse feature?

Or possibly look through the issues and find the simplest one's to fix that way we can close those issues.

Also if iLinked Doesn't plan to merge maybe we make new repo with a active person to allow commits?

**Comment by verticalsync** [comment]
> @verticalsync Are you able to implement the report abuse feature?
> 
> Or possibly look through the issues and find the simplest one's to fix that way we can close those issues.
> 
> Also if iLinked Doesn't plan to merge maybe we make new repo with a active person to allow commits?

iLinked won't merge because he is on vacation for like a week.

**Comment by not-ilinked** [comment]
> > @verticalsync Are you able to implement the report abuse feature?
> > 
> > Or possibly look through the issues and find the simplest one's to fix that way we can close those issues.
> > 
> > Also if iLinked Doesn't plan to merge maybe we make new repo with a active person to allow commits?
> 
> iLinked won't merge because he is on vacation for like a week.

Surprise it's been merged lol

**Comment by ptraced** [comment]
@not-ilinked you should close the issues and pull request's he mentioned and fixed 👍

**Pull request merged**
