### PR TITLE
Anarchy rewritten to support new discord

### PR DESCRIPTION
**Pull request by vpwl**
Plz

### CODE REVIEW

**Comment by xi-sln** [comment]
Please contirbute if u will

**Comment by xi-sln** [comment]
and merge

**Comment by purpl3r0se** [comment]
> Please contirbute if u will

ok hol on

**Comment by Euro-pol** [comment]
what the fuck

**Comment by purpl3r0se** [comment]
> what the fuck

ADD ME BACK ON DISCORD MONK

**Comment by Mrgaton** [comment]
> Plz

what are you thinking about?

**Pull request closed without merging**
